config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index new create show] do
      resources :comments, only: %i[create]
      resources :likes, only: %i[create]
    end
  end

  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates_associated :post, :author
  validates :text, presence: true

  before_destroy :decrement_post_comments_counter
  after_save :increment_post_comments_counter

  private

  def increment_post_comments_counter
    post.increment!(:comments_counter)
  end

  def decrement_post_comments_counter
    post.decrement!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates_associated :post, :author

  before_destroy :decrement_post_likes_counter
  after_save :increment_post_likes_counter

  private

  def increment_post_likes_counter
    post.increment!(:likes_counter)
  end

  def decrement_post_likes_counter
    post.decrement!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates_associated :author
  validates :title, length: { in: 1..250, message: 'the title should not exceed 250 char' }
  validates :text, presence: true
  validates :likes_counter, comparison: { greater_than_or_equal_to: 0 }
  validates :comments_counter, comparison: { greater_than_or_equal_to: 0 }

  before_destroy :decrement_user_posts_counter
  after_save :increment_user_posts_counter

  def five_recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def increment_user_posts_counter
    author.increment!(:posts_counter)
  end

  def decrement_user_posts_counter
    author.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }

  def tree_recent_posts
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_params, if: :devise_controller?

  protected

  def update_allowed_params
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :photo, :bio) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password, :photo, :bio)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)

    comment = post.comments.new(comments_params)
    comment.author = current_user

    respond_to do |format|
      format.html do
        if comment.save
          flash[:success] = 'Comment added!'
        else
          flash[:error] = 'Something went wrong'
        end
        redirect_back_or_to(post)
      end
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post_id = params[:post_id].to_i
    post = Post.find(post_id)

    like = post.likes.new
    like.author = current_user

    respond_to do |format|
      format.html do
        if like.save
          flash[:success] = 'Like added!'
        else
          flash[:error] = 'Something went wrong'
        end
        redirect_back_or_to(post)
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @current_user = current_user
    @current_user_id = current_user.id.to_i if current_user
    user_id = params[:user_id].to_i
    @user = User.includes(:posts).find(user_id)
    @posts = @user.posts.includes(:comments)
  end

  def new
    @current_user = current_user
    @current_user_id = current_user.id.to_i
    post_new = Post.new
    respond_to do |format|
      format.html { render :new, locals: { post: post_new } }
    end
  end

  def create
    post = current_user.posts.new(post_params)

    respond_to do |format|
      format.html do
        if post.save
          flash[:success] = 'Post added!'
        else
          flash[:error] = 'Something went wrong'
        end
        redirect_to user_posts_path(current_user)
      end
    end
  end

  def show
    @current_user = current_user
    post_id = params[:id].to_i
    @post = Post.includes(:comments).find(post_id)
    @liked = @current_user.likes.find_by(post: @post) if current_user
  end

  private

  def post_params
    params.require(:post).permit(:text, :title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :authenticate_user!

  def index
    @current_user = current_user
    @users = User.all
  end

  def show
    @current_user = current_user
    @user = User.includes(:posts, :comments).find(params[:id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- <%= javascript_importmap_tags %> -->
  </head>

  <body>
    <header class="flex-col align-center">
      <h1>Blog App</h1>
      <ul>
        <% if @current_user %>
          <li><%= link_to "Edit", edit_user_registration_path  %></li>
          <li><%= button_to "Sign Out", destroy_user_session_path, method: :delete  %></li> 
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path  %></li>
        <% end %>
      </ul>
    </header>
    <div class="flashes flex align-center">
      <h2><%= flash[:success] %></h2>
      <h2><%= flash[:error] %></h2>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
    
  </body>
</html>

app/views/posts/index.html.erb
<section id="posts-index">
    <div class="flex">
      <%= render "shared/user_container", user: @user %>
    </div>
    <% if @current_user %>
      <%= link_to "New Post", new_user_post_path(@current_user_id), class: "btn new-post" %>
    <% end %>
    
    <div>
      <ul class="posts flex-col">
        <%= render "shared/list_posts", posts: @posts.reverse %>
      </ul>
    </div>
</section>

app/views/posts/new.html.erb
<section id="new-post">
  <h2>New Post</h2>

  <%= form_with url: user_posts_path(@current_user_id), method: :post, local: true, scope: :post do |f| %>
    <div class="flex-col input-box">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="flex-col input-box" >
      <%= f.label :text %>
      <%= f.text_area :text %>
    </div>
    <%= f.submit "Submit", :class => "btn submit" %>
  <% end %>

</section>

app/views/posts/show.html.erb
<section id="posts-show">
  <div class="post">
    <div class="post-text border">
      <h2><%= @post.title %> by <%= @post.author.name%></h2>
      <br>
      <p class="more-info text-end" >Comments: <%= @post.comments_counter %>, Likes: <%= @post.likes_counter %></p>
      <p class="text"><%= @post.text %></p>
    </div>
    <div class="like">
      <% if @liked %>
        <p>Liked!</p>
      <% else %>
        <% if @current_user %>
          <%= form_with url: user_post_likes_path(@current_user, @post), scope: :like do |f| %>
            <%= f.submit "Like", :class => "btn btn-like" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <ul class="comments border">
      <%= render "shared/comments", comments: @post.comments %>
    </ul>
    <div class="new-comment">
      <% if @current_user %>
      <%= form_with url: user_post_comments_path(@current_user, @post), scope: :comment do |f| %>
        <div class="flex-col input-box">
          <%= f.label :text, "Add new comment" %>
          <%= f.text_area :text %>
        </div>
        <%= f.submit "Submit", :class => "btn submit" %>
      <% end %>
      <% end %>
    <div>
  </div>
</section>

app/views/shared/_comments.html.erb
<% comments.each do |comment| %>
  <li>
    <p><strong><%= comment.author.name %>: </strong></p>
    <p class="text">
      <%= comment.text %>
    </p>
    <br>
  </li>
<% end %>

app/views/shared/_list_posts.html.erb
<% posts.each do |post| %>
  <li class="flex-col border post-info">
    <%= link_to user_post_path(@user, post), class:"flex-col" do %>
      <div class="post-details">
      <h4 class="title"><%= truncate post.title, length: 100 %></h4>
      <p class="text"><%= truncate post.text, length: 100 %></p>
      <p class="more-info text-end">
        Comments: <%= post.comments_counter %>, Likes: <%= post.likes_counter %>
      </p>
      </div>
      <ul class="comments">
        <%= render "shared/comments", comments: post.five_recent_comments %>
      </ul>
    <% end %>
  </li>
<% end %>

app/views/shared/_user_container.html.erb
<%= image_tag user.photo || '', class: 'user-avatar sm' %>
<div class="details flex-col border">
  <h3><%= user.name %></h3>
  <p class="text-end">Number of posts: <%= user.posts_counter %></p>
</div>

app/views/users/index.html.erb
<section id="users-index">
  <ul class="user-info flex-col">
    <% unless @users.empty? %>
      <% @users.each do |user| %>
        <li>
        <%= link_to(user) do %>
           <%= render "shared/user_container", user: user %> 
        <% end %>
      <% end %>
    <% end %>
  </ul>
</section>

app/views/users/show.html.erb
<section id="users-show" class="flex-col">
  <ul class="user-info flex-col">
    <li class="flex">
      <%= render "shared/user_container", user: @user %>
    </li>

    <li class="bio flex-col border">
      <h4>Bio</h4>
      <p><%= @user.bio %></p>
    </li>

    <li class="posts">
      <ul class="flex-col">
        <%= render "shared/list_posts", posts: @user.tree_recent_posts %>
      </ul>
    </li>
  </ul>
  <%= link_to "See all posts", "#{@user.id}/posts", class: "btn see-all" %>
</section>